### ISSUE TITLE
Need to change the selector where font-family is declared

### ISSUE THREAD

**Issue by mr-alien** [Keyamoon/IcoMoon-Free#7]
Recently while using IcoMoon I used something like this

`<span class="icon-sound" data-tooltip="Whatever is here"></span>`

So here my tooltips inherits the `font-family` of icomoon instead of inheriting the default `font-family`. 
For example if we use something like this

    [data-tooltip]:hover:after {
        content: attr(data-tooltip);
        white-space: nowrap;
        /* Other stylings */

        font-family: Arial; /* Need to specify the font-family else it inherits icomoon */
    }

Solution is to declare it on the `:before` pseudo instead like

    [class^="icon-"]:before, 
    [class*=" icon-"]:before {
	    font-family: 'icomoon';
	    speak: none;
	    font-style: normal;
	    font-weight: normal;
	    font-variant: normal;
	    text-transform: none;
    	    line-height: 1;
	    -webkit-font-smoothing: antialiased;
	    -moz-osx-font-smoothing: grayscale;
    }

**Comment by Keyamoon** [comment]
That would cause some other issues. Read the answer given here to learn more: https://groups.google.com/forum/#!starred/icomoon/4caffAUh0V0

I suggest you to use a parent <code>&lt;span&gt;</code> to solve your tooltip problem.
