### ISSUE TITLE
IcoMoon App failed to load

### ISSUE THREAD

**Issue by rajlaksh** [Keyamoon/IcoMoon-Free#8]
IcoMoon App failed to load .

So Please fix
https://icomoon.io/app/#/select

**Comment by Keyamoon** [comment]
What is your browser? In what OS?

**Comment by rajlaksh** [comment]
Mozilla Firefox 37.0.1

It show keep loading when i use console it show JS errors.

**Comment by Keyamoon** [comment]
Are you in private mode of Firefox?

**Comment by rajlaksh** [comment]
yes.

**Comment by Keyamoon** [comment]
IcoMoon uses local storage and indexedDB for caching. Private modes of some browsers don't allow that. As a result, the app wouldn't load. I will try to find a solution. But for now, you can load the app if you get out of the private mode or use Chrome.

**Comment by rajlaksh** [comment]
I use normal mode it didn't work :(

**Comment by Keyamoon** [comment]
It works fine for me in the normal mode. You have probably changed your settings or disabled localStorage or indexedDB.

**Comment by rajlaksh** [comment]
Yes, It work in Normal Mode Now.  I don't know why before.

Thanks for helping :+1:
